select 
FD.ID,
A.ACCT_CODE, A.ACCT_NAME, A.ECORE_CUST_ACCT,A.ECORE_CUST_NAME,
--STILL TO ADD Account Revenue model, WOA Advance Cash?
DATE(R.CREATED_TS) AS "Request Date", /*R.STATUS_ID,*/RS.NAME AS REQUEST_STATUS, 
FD.JOURNAL_ACRONYM,FD.JOURNAL_NAME,FD.JOURNAL_PISSN, FD.JOURNAL_EISSN,
FD.AID, FD.MANUSCRIPT_ID, FD.ARTICLE_NAME as "Article Title", 
R.SUBMITTING_AUTHOR_NAME||' ('||R.SUBMITTING_AUTHOR_EMAIL||')' as "Submitting author (email)",
AUTH.NAME as "Corresponding author",
AUTH.EMAIL as "Corresponding author email",
AUTH.ORCID_ID as "Corresponding author ORCiD",
GD.CoAuthors as "Co-authors (name, email, ORCiD)",
--STILL TO ADD  Corresponding author, Corresponding author email, Corresponding author ORCiD, Co-authors (name, email, ORCiD)
FD.DOI, 
--still to add article URL, FD.JOURNAL_WOL_URL is the journal level URL,
FD.DH_ID,FD.CATEGORY,FD.LICENSE_SUB_TYPE, FD.JOURNAL_REVENUE_MODEL,
--STILL TO ADD CURRENCY, 
R.ARTICLE_PRICE, R.ARTICLE_DISCOUNT, R.ALLOCATED_AMOUNT AS "Amount Charged",R.ALLOCATED_DATE AS "Amount Charged - Date",
FD.ACCEPTED_TS,FD.PRODUCTION_RECEIVED_DATE
--STILL TO ADD EV Published Date, Published in Issue Date
--STILL TO ADD PUBLICATION STATUS, INSTITUTIONS,ADMIN NOTES, USER NOTES
--,FD.*
FROM  "PROD_EDW"."AS"."FD_ARTICLE" FD
left JOIN "PROD_EDW"."AS"."REQUEST" R  ON R.ARTICLE_ID = FD.ID --note the differences in field name
LEFT JOIN "PROD_EDW"."AS"."ACCOUNT" A ON R.ACCOUNT_ID = A.ID --note the differences in field name
left join "PROD_EDW"."AS"."REQUEST_STATUS" RS ON R.STATUS_ID = RS.ID --note the differences in field name
LEFT JOIN (
SELECT P.NAME, P.EMAIL, P.ORCID_ID, TRY_TO_NUMERIC(REL.ENTITY_ID) as DH_ID
FROM "PROD_EDW"."AS"."PARTICIPANTS" P
LEFT JOIN "PROD_EDW"."AS"."RELATIONSHIPS" REL on REL.PARTICIPANT_ID = P.ID 
WHERE REL.ROLE_ID = 'correspondingAuthorOf') AUTH on FD.DH_ID = AUTH.DH_ID


LEFT JOIN (
SELECT TRY_TO_NUMERIC(REL2.ENTITY_ID) as DH_ID , LISTAGG(DISTINCT PD.COAUTHOR,', ') as CoAuthors
FROM(
SELECT P2.ID, P2.FAMILY_NAME as SURNAME, (P2.NAME || ' (' || P2.EMAIL || '; ORCID ID: ' || P2.ORCID_ID ||')') as COAUTHOR
FROM "PROD_EDW"."AS"."PARTICIPANTS" P2) PD
LEFT JOIN "PROD_EDW"."AS"."RELATIONSHIPS" REL2 on REL2.PARTICIPANT_ID = PD.ID
WHERE REL2.ROLE_ID = 'authorOf' 
GROUP BY DH_ID) GD on GD.DH_ID = FD.DH_ID



WHERE A.ACCT_NAME LIKE ('%DEAL%')