select DISTINCT
AUTHOR.EMAIL_ADDRESS,
AUTHOR.AUTHOR_FIRST_NAME,
AUTHOR.AUTHOR_LAST_NAME,
ADR.AUTHOR_STANDARDIZED_NAME, --I'd always include standardized name in author data, institute + standardized name is generally how we link things so it's useful to have
adr.INSTITUTE, --I'd always include institute in author data, institute + standardized name is generally how we link things so it's useful to have
ADR.AUTHOR_COUNTRY,
ARTS.YEAR_PUBLISHED,
ARTS.DOI AS ARTICLE_DOI,
ARTS.ARTICLE_TITLE,
PRODMAP.DATASALON_CODE,
ARTS.PUBLICATION_NAME,
JANIS.SECTION_TITLE AS JOURNAL_TITLE, -- I'd personally avoid using JANIS unless you have to. Better to get journal titles form ARTICLE_EXTN, PUBLICATION_NAME (if everything is an EBAC title) or STG_LKP_PRODUCT, DATASALON_PRODUCT_TTILE (if some things aren't EBAC titles) as a matter of course. It also means generally speaking it's one less table to use.
JANIS.DOI AS JOURNAL_DOI,
ARTS.EISSN AS ONLINE_ISSN --For Wiley titles this actually might be better from JANIS! Native WoS ISSN's are not great and I can't remember if we clean them or not.  

FROM PROD_EDW.EBAC.DW_ARTICLE_EXTN ARTS
INNER JOIN PROD_EDW.EBAC.DW_AUTHOR AUTHOR ON AUTHOR.ARTICLE_ID = ARTS.ARTICLE_ID
LEFT OUTER JOIN PROD_EDW.EBAC.DW_AUTHOR_ADDRESS_EXTN ADR ON ADR.ARTICLE_ID = AUTHOR.ARTICLE_ID AND ADR.AUTHOR_ID = AUTHOR.AUTHOR_ID
LEFT OUTER JOIN PROD_EDW.DS.STG_LKP_PRODUCT PRODMAP ON PRODMAP.EBAC_JOURNAL_ID = ARTS.JOURNAL_ID
LEFT OUTER JOIN PROD_EDW.RESEARCH.V_IC_JANIS_ONE_ROW_PER_GROUP_CODE JANIS ON JANIS.JOURNAL_GROUP_CODE = PRODMAP.DATASALON_CODE 
        
WHERE ARTS.PUBLISHER_GROUP = 'WILEY'
AND ARTS.YEAR_PUBLISHED IN (2020)
AND ARTS.EARLY_ACCESS = 0
AND ARTS.CITABLE_ITEM = 1
AND AUTHOR.EMAIL_ADDRESS IS NOT NULL
AND arts.PUBLICATION_NAME IN ('EMBO MOLECULAR MEDICINE','EMBO REPORTS','EMBO JOURNAL','MOLECULAR SYSTEMS BIOLOGY')

;
