///Code needed for Lucid Charts to create ERD
// This is based on SQLSERVER data load, ensure that is selected. 

SELECT 
'sqlserver' as dbms
,t.TABLE_CATALOG
,t.TABLE_SCHEMA
,t.TABLE_NAME
,c.COLUMN_NAME
,c.ORDINAL_POSITION
,c.DATA_TYPE
,c.CHARACTER_MAXIMUM_LENGTH
,sc.CONSTRAINT_TYPE 
,tp.TABLE_SCHEMA 
,tp.TABLE_NAME 
,'' as COLUMN_NAME 


FROM INFORMATION_SCHEMA.TABLES t 
LEFT JOIN INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_CATALOG=c.TABLE_CATALOG AND t.TABLE_SCHEMA=c.TABLE_SCHEMA AND t.TABLE_NAME=c.TABLE_NAME 
Left Join INFORMATION_SCHEMA.TABLE_CONSTRAINTS sc on sc.TABLE_NAME  = t.TABLE_NAME
Left Join INFORMATION_SCHEMA.TABLE_PRIVILEGES as TP on TP.TABLE_NAME = t.TABLE_NAME

 
 WHERE t.TABLE_TYPE='BASE TABLE' // This only brings in the Base Tables. 
 
 ;
  
///CR created to view info with the schema.  

SELECT Distinct 
t.TABLE_CATALOG
,t.TABLE_SCHEMA
,t.TABLE_NAME
,t.TABLE_TYPE
,t.LAST_ALTERED 
,lh.ROW_COUNT
,lh.LAST_LOAD_TIME

FROM INFORMATION_SCHEMA.TABLES t 
Left Join INFORMATION_SCHEMA.LOAD_HISTORY lh on t.

;
